version: "3.9"

networks:
  proxy: # docker network create --internal=false --attachable proxy
    attachable: true
    internal: false
    name: proxy

volumes:
  traefik-letsencrypt-volume:

services:
  traefik:
    image: traefik:v2.4.9
    restart: always
    container_name: server-traefik
    networks:
      - proxy
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      # traefik needs the docker socket in order to work properly
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-letsencrypt-volume:/letsencrypt
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.wildcard-certs.tls.domains[0].main=${DOMAIN}
      - traefik.http.routers.wildcard-certs.tls.domains[0].sans=*.${DOMAIN}
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=user:$$2y$$05$$MZ29B0k0q7DhDzCoQtAJXuknGjd0/6/AoSnw2KzmtYdgzkQTeDsVG
      #      - traefik.http.middlewares.hosthdr.headers.stsseconds=31536000
      #      - traefik.http.middlewares.hosthdr.headers.stsincludesubdomains=true
      #      - traefik.http.middlewares.hosthdr.headers.stspreload=true
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certresolver=letsencrypt
      - traefik.http.services.dashboard-service.loadbalancer.server.port=888
    command:
      - --api=true
      - --api.dashboard=true
      - --api.debug=false
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.swarmMode=false
      - --providers.docker.exposedbydefault=false
      - --log.filePath=/traefik.log
      - --log.level=INFO
      - --accesslog=false
      - --entryPoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=false
      - --entryPoints.websecure.address=:443
      # letsencrypt
      - --certificatesresolvers.letsencrypt.acme.email=alert@goodbit.dev
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # used during the challenge
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --pilot.token=0b15cdd6-1726-438e-8bea-28d82fe020db
